spring:
  application:
    name: notification-service
  config:
    import:
      optional:config-server:
  cloud:
    config:
      uri: http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.notificationservice: DEBUG
    org.springframework.kafka: INFO